# .github/workflows/release.yml
steps:
  - uses: actions/checkout@v4

  - name: Build .app (unsigned)
    run: |
      xcodebuild -scheme AutoScreenshooter \
                 -configuration Release \
                 CODE_SIGNING_ALLOWED=NO \
                 CODE_SIGNING_REQUIRED=NO \
                 CODE_SIGN_IDENTITY="" \
                 -derivedDataPath build \
                 build

  - name: Zip bundle
    run: |
      APP_PATH="build/Build/Products/Release/AutoScreenshooter.app"
      [ -d "$APP_PATH" ] || { echo "::error ::Bundle not found"; exit 1; }
      ditto -c -k --sequesterRsrc --keepParent "$APP_PATH" AutoScreenshooter.zip

  - name: Create Release & upload
    uses: ncipollo/release-action@v1
    with:
      artifacts: AutoScreenshooter.zip
      artifactContentType: application/zip