steps:
  - uses: actions/checkout@v4

  - name: Build with SwiftPM
    run: swift build -c release

  - name: Make .app bundle
    run: |
      chmod +x make_app.sh
      ./make_app.sh            # creates .build/release/AutoScreenshooter.app

  - name: Zip bundle
    run: |
      ditto -c -k --sequesterRsrc --keepParent \
            .build/release/AutoScreenshooter.app \
            AutoScreenshooter.zip

  - name: Create Release & upload
    uses: ncipollo/release-action@v1
    with:
      artifacts: AutoScreenshooter.zip
      artifactContentType: application/zip